#!/usr/bin/env python3
"""Generate package, CLI, pytest, and import maps for the documentation."""

from __future__ import annotations

import argparse
import ast
import html
import importlib.util
import os
import re
from collections import defaultdict
from collections.abc import Iterable
from pathlib import Path

GENERATED_NOTICE = ".. Generated by tools/generate_code_map.py; do not edit by hand.\n\n"


def breakable_code(value: str) -> str:
    """Return inline code that can wrap in both LaTeX and HTML output."""
    html_value = html.escape(value, quote=False)
    return rf":raw-latex:`\path{{{value}}}`\ :raw-html:`<code>{html_value}</code>`"


def python_module(path: Path, package_root: Path) -> str:
    """Return the dotted module name for a Python file below ``package_root``."""
    relative = path.relative_to(package_root.parent).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def python_files(package_root: Path) -> list[Path]:
    """Return package Python files in a stable order."""
    return sorted(path for path in package_root.rglob("*.py") if "__pycache__" not in path.parts)


def source_index(package_root: Path) -> tuple[dict[str, Path], set[str]]:
    """Return known modules and top-level functions/classes/methods."""
    modules = {}
    symbols = set()
    for path in python_files(package_root):
        module = python_module(path, package_root)
        modules[module] = path
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                symbols.add(f"{module}.{node.name}")
            elif isinstance(node, ast.ClassDef):
                class_name = f"{module}.{node.name}"
                symbols.add(class_name)
                for child in node.body:
                    if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        symbols.add(f"{class_name}.{child.name}")
    return modules, symbols


def _ascii_tree(path: Path, prefix: str = "") -> list[str]:
    directories = sorted(
        child
        for child in path.iterdir()
        if child.is_dir()
        and child.name != "__pycache__"
        and any(descendant.suffix == ".py" for descendant in child.rglob("*.py"))
    )
    files = sorted(child for child in path.iterdir() if child.is_file() and child.suffix == ".py")
    entries = [*directories, *files]
    lines = []
    for index, entry in enumerate(entries):
        last = index == len(entries) - 1
        connector = "`-- " if last else "|-- "
        suffix = "/" if entry.is_dir() else ""
        lines.append(f"{prefix}{connector}{entry.name}{suffix}")
        if entry.is_dir():
            extension = "    " if last else "|   "
            lines.extend(_ascii_tree(entry, prefix + extension))
    return lines


def package_tree(package_root: Path) -> str:
    """Return an ASCII tree containing the Python package only."""
    return "\n".join([f"{package_root.name}/", *_ascii_tree(package_root)])


def project_scripts(pyproject: Path) -> dict[str, str]:
    """Read ``[project.scripts]`` without requiring a TOML dependency."""
    scripts = {}
    in_scripts = False
    assignment = re.compile(r'^\s*([A-Za-z0-9_.-]+)\s*=\s*["\']([^"\']+)["\']\s*$')
    for line in pyproject.read_text(encoding="utf-8").splitlines():
        if line.startswith("["):
            in_scripts = line.strip() == "[project.scripts]"
            continue
        if not in_scripts or not (match := assignment.match(line)):
            continue
        command, target = match.groups()
        scripts[command] = target.split(":", maxsplit=1)[0]
    return scripts


def cli_modules(package_root: Path) -> list[str]:
    """Return executable-looking modules below ``fd2bec.cli``."""
    cli_root = package_root / "cli"
    return [
        python_module(path, package_root)
        for path in python_files(cli_root)
        if path.name != "__init__.py"
    ]


def documentation_texts(root: Path, generated_root: Path) -> dict[Path, str]:
    """Return manually maintained documentation, excluding generated maps."""
    candidates = [root / "README.md", root / "docs" / "README.md"]
    candidates.extend((root / "docs" / "source").rglob("*.rst"))
    candidates.extend((root / "fd2bec").rglob("README.md"))
    texts = {}
    for path in sorted(set(candidates)):
        if not path.is_file() or generated_root in path.parents:
            continue
        texts[path] = path.read_text(encoding="utf-8")
    return texts


def documented_at(command: str | None, module: str, docs: dict[Path, str]) -> Path | None:
    """Find explicit command/module documentation, if any."""
    stem = module.rsplit(".", maxsplit=1)[-1]
    patterns = [
        re.compile(rf"(?m)^\s*{re.escape(stem)}(?:\.py)?(?:\s|$)"),
        re.compile(rf"``{re.escape(stem)}(?:\.py)?``"),
        re.compile(re.escape(module)),
    ]
    if command:
        patterns.extend(
            [
                re.compile(rf"(?m)^\s*{re.escape(command)}(?:\s|$)"),
                re.compile(rf"``{re.escape(command)}``"),
                re.compile(rf"`{re.escape(command)}`"),
            ]
        )
    for path, text in docs.items():
        if any(pattern.search(text) for pattern in patterns):
            return path
    return None


def _import_aliases(tree: ast.AST) -> dict[str, str]:
    aliases = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for imported in node.names:
                if imported.name == "fd2bec" or imported.name.startswith("fd2bec."):
                    alias = imported.asname or imported.name.split(".")[0]
                    aliases[alias] = imported.name if imported.asname else "fd2bec"
        elif isinstance(node, ast.ImportFrom) and node.level == 0:
            if not node.module or not (
                node.module == "fd2bec" or node.module.startswith("fd2bec.")
            ):
                continue
            for imported in node.names:
                candidate = f"{node.module}.{imported.name}"
                aliases[imported.asname or imported.name] = candidate
    return aliases


def _attribute_parts(node: ast.AST) -> list[str] | None:
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if not isinstance(node, ast.Name):
        return None
    return [node.id, *reversed(parts)]


def _attribute_root(node: ast.Attribute) -> ast.Name | None:
    """Return the root name of an attribute chain, when it has one."""
    value: ast.AST = node
    while isinstance(value, ast.Attribute):
        value = value.value
    return value if isinstance(value, ast.Name) else None


def _longest_symbol(reference: str, symbols: set[str]) -> str | None:
    parts = reference.split(".")
    for stop in range(len(parts), 1, -1):
        candidate = ".".join(parts[:stop])
        if candidate in symbols:
            return candidate
    return None


def _test_functions(tree: ast.Module) -> Iterable[tuple[str, ast.AST]]:
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
            "test"
        ):
            yield node.name, node
        elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
            for child in node.body:
                if isinstance(
                    child, (ast.FunctionDef, ast.AsyncFunctionDef)
                ) and child.name.startswith("test"):
                    yield f"{node.name}::{child.name}", child


def pytest_symbol_map(tests_root: Path, symbols: set[str]) -> dict[str, set[str]]:
    """Map directly referenced fd2bec symbols to pytest node identifiers."""
    related = defaultdict(set)
    for path in sorted(tests_root.rglob("test*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        module_aliases = _import_aliases(tree)
        for test_name, test_node in _test_functions(tree):
            aliases = dict(module_aliases)
            aliases.update(_import_aliases(test_node))
            test_id = f"tests/{path.relative_to(tests_root)}::{test_name}"
            attribute_roots = {
                id(root)
                for node in ast.walk(test_node)
                if isinstance(node, ast.Attribute)
                if (root := _attribute_root(node)) is not None
            }
            for node in ast.walk(test_node):
                parts = _attribute_parts(node) if isinstance(node, ast.Attribute) else None
                if parts and parts[0] in aliases:
                    reference = ".".join([aliases[parts[0]], *parts[1:]])
                elif (
                    isinstance(node, ast.Name)
                    and id(node) not in attribute_roots
                    and node.id in aliases
                ):
                    reference = aliases[node.id]
                else:
                    continue
                if symbol := _longest_symbol(reference, symbols):
                    related[symbol].add(test_id)
    return dict(related)


def _relative_import_module(node: ast.ImportFrom, module: str, is_package: bool) -> str:
    package = module if is_package else module.rpartition(".")[0]
    relative = "." * node.level + (node.module or "")
    return importlib.util.resolve_name(relative, package)


def module_dependencies(modules: dict[str, Path]) -> dict[str, set[str]]:
    """Return direct internal imports for each module."""
    known = set(modules)
    dependencies = defaultdict(set)
    for module, path in modules.items():
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        is_package = path.name == "__init__.py"
        for node in ast.walk(tree):
            targets = []
            if isinstance(node, ast.Import):
                targets.extend(imported.name for imported in node.names)
            elif isinstance(node, ast.ImportFrom):
                base = (
                    _relative_import_module(node, module, is_package) if node.level else node.module
                )
                if base:
                    targets.append(base)
                    targets.extend(f"{base}.{imported.name}" for imported in node.names)
            for target in targets:
                if target != "fd2bec" and not target.startswith("fd2bec."):
                    continue
                parts = target.split(".")
                resolved = None
                for stop in range(len(parts), 0, -1):
                    candidate = ".".join(parts[:stop])
                    if candidate in known:
                        resolved = candidate
                        break
                if resolved and resolved != module:
                    dependencies[module].add(resolved)
    return dict(dependencies)


def subsystem(module: str, cli_groups: set[str]) -> str:
    """Collapse a module into a readable dependency-graph subsystem."""
    parts = module.split(".")
    if len(parts) == 1:
        return "fd2bec"
    if parts[1] != "cli":
        return parts[1]
    if len(parts) >= 3 and parts[2] in cli_groups:
        return f"cli.{parts[2]}"
    return "cli"


def subsystem_dependencies(
    dependencies: dict[str, set[str]], cli_groups: set[str]
) -> dict[str, set[str]]:
    """Collapse module imports into subsystem imports."""
    collapsed = defaultdict(set)
    for source, targets in dependencies.items():
        source_group = subsystem(source, cli_groups)
        for target in targets:
            target_group = subsystem(target, cli_groups)
            if source_group != target_group:
                collapsed[source_group].add(target_group)
    return dict(collapsed)


def dependency_dot(dependencies: dict[str, set[str]], rankdir: str = "TB") -> str:
    """Render subsystem dependencies as Graphviz DOT."""
    nodes = sorted(
        set(dependencies) | {target for targets in dependencies.values() for target in targets}
    )
    size = ', size="5.5,5.0"'
    lines = [
        "digraph fd2bec_dependencies {",
        f'  graph [rankdir="{rankdir}", bgcolor="transparent", pad="0.2", '
        f'nodesep="0.2", ranksep="0.35", ratio="compress"{size}];',
        '  node [shape="box", style="rounded,filled", fontname="Helvetica", fontsize="9", color="#365f7d"];',
        '  edge [color="#667788", arrowsize="0.65"];',
    ]
    for node in nodes:
        color = "#fff2cc" if node.startswith("cli") else "#d9eaf7"
        lines.append(f'  "{node}" [fillcolor="{color}"];')
    for source in sorted(dependencies):
        for target in sorted(dependencies[source]):
            lines.append(f'  "{source}" -> "{target}";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def _module_test_files(module: str, related: dict[str, set[str]]) -> list[Path]:
    """Return pytest files that directly reference a module's public symbols."""
    tests = {
        test
        for symbol, symbol_tests in related.items()
        if symbol.startswith(f"{module}.")
        for test in symbol_tests
    }
    return sorted({Path(test.split("::", maxsplit=1)[0]) for test in tests})


def _script_description(path: Path) -> str:
    """Return the short description declared by a CLI script."""
    def first_sentence(text: str) -> str:
        text = " ".join(text.split())
        return re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and any(isinstance(target, ast.Name) and target.id == "description" for target in node.targets)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            return first_sentence(node.value.value)
    docstring = ast.get_docstring(tree)
    if docstring:
        return first_sentence(docstring)
    return path.stem.replace("_", " ").capitalize() + "."


def _download_link(path: Path, generated_root: Path, root: Path) -> str:
    """Link to a repository file from a generated Sphinx include fragment."""
    # Sphinx resolves a role inside an ``include`` relative to the including
    # document (``docs/source/package_structure.rst``), not the fragment.
    target = Path(os.path.relpath(path, generated_root.parent)).as_posix()
    label = path.relative_to(root).as_posix()
    return f":download:`{label} <{target}>`"


def package_structure_rst(
    root: Path,
    package_root: Path,
    modules: dict[str, Path],
    related: dict[str, set[str]],
    generated_root: Path,
) -> str:
    scripts = project_scripts(root / "pyproject.toml")
    inventory = sorted(
        (command, module, modules[module])
        for command, module in scripts.items()
        if module in modules and module.startswith("fd2bec.cli.")
    )

    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "Command inventory",
        "-----------------",
        "",
        "Each entry links to its source file. The inventory is generated from",
        "``[project.scripts]`` and therefore follows the installed command names.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 38 20 42",
        "",
        "   * - File path",
        "     - Script",
        "     - Description",
    ]
    for command, _module, path in inventory:
        lines.extend(
            [
                f"   * - {_download_link(path, generated_root, root)}",
                f"     - {breakable_code(command)}",
                f"     - {_script_description(path)}",
            ]
        )

    lines.extend(["", "Related pytest files", "--------------------", ""])
    for command, module, path in inventory:
        tests = set(_module_test_files(module, related))
        conventional_test = root / "tests" / f"test_{path.stem}.py"
        if conventional_test.is_file():
            tests.add(conventional_test.relative_to(root))
        test_links = (
            ", ".join(
                _download_link(root / test, generated_root, root) for test in sorted(tests)
            )
            if tests
            else "No direct pytest reference"
        )
        lines.append(f"* {breakable_code(command)}: {test_links}")
    return "\n".join(lines) + "\n"


def pytest_map_rst(related: dict[str, set[str]]) -> str:
    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "Direct symbol-to-pytest relationships",
        "-------------------------------------",
        "",
        "This is a static direct-use map, not a runtime coverage report. It records a",
        "relationship when a pytest function directly references an imported fd2bec",
        "function, class, or method. Indirect calls through another function are not",
        "expanded. Each compact row is ``symbol: directly related pytest functions``.",
        "",
    ]
    by_module = defaultdict(list)
    for symbol, tests in related.items():
        module, _, short_name = symbol.rpartition(".")
        by_module[module].append((short_name, tests))
    for module in sorted(by_module):
        lines.extend([module, "~" * len(module), ""])
        for short_name, tests in sorted(by_module[module]):
            test_list = "; ".join(breakable_code(test) for test in sorted(tests))
            lines.append(f"* {breakable_code(short_name)}: {test_list}")
        lines.append("")
    return "\n".join(lines) + "\n"


def dependencies_rst(dependencies: dict[str, set[str]]) -> str:
    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "Direct subsystem imports",
        "------------------------",
        "",
        "An arrow ``A -> B`` means that at least one module in subsystem ``A``",
        "directly imports a module from subsystem ``B``.",
        "",
    ]
    for source in sorted(dependencies):
        targets = ", ".join(breakable_code(target) for target in sorted(dependencies[source]))
        lines.append(f"* {breakable_code(source)} -> {targets}")
    return "\n".join(lines) + "\n"


def generate(root: Path, output: Path) -> None:
    """Generate every code-map artifact."""
    package_root = root / "fd2bec"
    modules, symbols = source_index(package_root)
    related = pytest_symbol_map(root / "tests", symbols)
    cli_groups = {path.name for path in (package_root / "cli").iterdir() if path.is_dir()}
    dependencies = subsystem_dependencies(module_dependencies(modules), cli_groups)
    workflow_cli = {
        "cli.aims",
        "cli.dFdE",
        "cli.dPdR",
        "cli.dPdS",
        "cli.qe",
    }
    core_dependencies = {
        source: targets for source, targets in dependencies.items() if not source.startswith("cli")
    }
    workflow_dependencies = {
        source: targets for source, targets in dependencies.items() if source in workflow_cli
    }
    utility_dependencies = {
        source: targets
        for source, targets in dependencies.items()
        if source.startswith("cli") and source not in workflow_cli
    }

    output.mkdir(parents=True, exist_ok=True)
    (output / "package_structure.inc").write_text(
        package_structure_rst(root, package_root, modules, related, output), encoding="utf-8"
    )
    (output / "pytest_map.inc").write_text(pytest_map_rst(related), encoding="utf-8")
    (output / "dependencies.inc").write_text(dependencies_rst(dependencies), encoding="utf-8")
    (output / "core_dependencies.dot").write_text(
        dependency_dot(core_dependencies), encoding="utf-8"
    )
    (output / "workflow_cli_dependencies.dot").write_text(
        dependency_dot(workflow_dependencies, rankdir="LR"), encoding="utf-8"
    )
    (output / "utility_cli_dependencies.dot").write_text(
        dependency_dot(utility_dependencies, rankdir="LR"), encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (default: inferred from this script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="generated documentation directory (default: docs/source/generated)",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output.resolve() if args.output else root / "docs" / "source" / "generated"
    generate(root, output)


if __name__ == "__main__":
    main()
