from collections import defaultdict
from pathlib import Path

CLI_ROOT = Path("fd2bec/cli")
COMMAND_NAMES = {Path("fd2bec_help.py"): "fd2bec-help"}


def main():
    groups = defaultdict(list)

    for py in CLI_ROOT.rglob("*.py"):
        if py.name == "__init__.py":
            continue

        # e.g. quantumsparse/cli/diagonalization/diagonalize.py
        rel = py.relative_to(CLI_ROOT)

        # top-level folder under cli/
        folder = rel.parts[0] if len(rel.parts) > 1 else "root"

        module = ".".join(py.with_suffix("").parts)
        name = COMMAND_NAMES.get(rel, py.stem)

        groups[folder].append(f'{name} = "{module}:main"')

    print("\n\n# This part is auto-generated by tools/initialize.py")
    print("[project.scripts]\n")

    for folder in sorted(groups):
        print(f"# --- {folder.replace('_', ' ')} ---")
        for line in sorted(groups[folder]):
            print(line)
        print()  # blank line between groups


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
