[project]
name = "fd2bec"
version = "0.0.0"
description = "A python package to efficiently evaluate Born Effective Charges using Finite Differences."
authors = [
    { name = "Elia Stocco", email = "eliastocco@gmail.com" }
]
requires-python = ">=3.9"

dependencies = [
    "numpy",
    # "scipy",
    "pandas",
    "typing-extensions",  # For better compatibility with type hints
    "matplotlib",
    "argparse",
    "dataclasses; python_version < '3.10'",  # Built-in from Python 3.10+
    "tqdm",
    "pathlib",
    "spglib",
    "ase",
    "pymatgen",
]

[project.optional-dependencies]
dev = [
    "pylint",
    "pre-commit",
    "ruff",
    "isort",
    "black==24.8.0",
    "pytest",
    "pytest-cov",
]
mace-polar = [
    "mace-torch>=0.3.16",
    "graph-longrange @ git+https://github.com/WillBaldwin0/graph_electrostatics.git@v0.4.0",
]

# dev-mp = [
#     "pylint",
#     "pre-commit",
#     "ruff",
#     "isort",
#     "black==24.8.0",
#     "pytest",
#     "pytest-cov",
#     "mp-api",
#     "python_requires>=3.11; python_version < '3.11'"
# ]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
fd2bec = ["structures/*.extxyz", "*.mplstyle"]

[tool.setuptools.packages.find]
include = ["fd2bec*"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E741","E501"]  # only this one

[tool.black]
line-length = 100
